### ISSUE TITLE
Add option for 'Light Mode'

### ISSUE THREAD

**Issue by punyets** [stevenaeola/progblack_2324#16]
There must be a light mode for the minority

**Comment by rileyhutton** [comment]
I believe this already exists
<img width="252" alt="Screenshot 2023-10-13 at 13 30 30" src="https://github.com/stevenaeola/progblack_2324/assets/80292379/9bae77f4-b829-4ea8-b98e-a17fa95bf94a">

**Comment by punyets** [comment]
tnx man
